/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import mainApp.mainApp;
import net.proteanit.sql.DbUtils;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import task.entity.Login;
import task.entity.Student;

/**
 *
 * @author Ziad Alymany
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        go = new javax.swing.JButton();
        search_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        add_name = new javax.swing.JTextField();
        add_id = new javax.swing.JTextField();
        add_phn = new javax.swing.JTextField();
        add_dept = new javax.swing.JComboBox<>();
        add_save = new javax.swing.JButton();
        add_cancel = new javax.swing.JButton();
        jFrame5 = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        update_name = new javax.swing.JTextField();
        update_id = new javax.swing.JTextField();
        update_phn = new javax.swing.JTextField();
        update_dept = new javax.swing.JComboBox<>();
        update_save = new javax.swing.JButton();
        update_cancel = new javax.swing.JButton();
        jFrame4 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        delete_yes = new javax.swing.JButton();
        delete_no = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lgn_user = new javax.swing.JTextField();
        lgn_pass = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Student View");
        jFrame1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jFrame1.setLocation(new java.awt.Point(365, 200));
        jFrame1.setPreferredSize(new java.awt.Dimension(626, 258));
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(626, 258));

        jPanel2.setMinimumSize(new java.awt.Dimension(595, 215));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 220));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clear.setText("reset");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        go.setText("go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Serach:");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTable1.setName("tview"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(go)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delete)
                        .addComponent(update))
                    .addComponent(add)
                    .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(search_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(go)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setTitle("Add Student");
        jFrame2.setBounds(new java.awt.Rectangle(0, 0, 255, 190));
        jFrame2.setLocation(new java.awt.Point(450, 250));
        jFrame2.setPreferredSize(new java.awt.Dimension(300, 243));
        jFrame2.setResizable(false);
        jFrame2.setSize(new java.awt.Dimension(300, 243));
        jFrame2.setType(java.awt.Window.Type.POPUP);

        jPanel3.setPreferredSize(new java.awt.Dimension(255, 190));

        jLabel4.setText("Name:");

        jLabel5.setText("Department:");

        jLabel6.setText("National ID:");

        jLabel7.setText("Phone Number:");

        add_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_nameActionPerformed(evt);
            }
        });

        add_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--choose a department--", "Computers", "Electrical", "Architecture", "Civil" }));

        add_save.setText("Save");
        add_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_saveActionPerformed(evt);
            }
        });

        add_cancel.setText("cancel");
        add_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_id)
                    .addComponent(add_dept, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_phn))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_save)
                .addGap(31, 31, 31)
                .addComponent(add_cancel)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(add_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(add_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(add_phn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_save)
                    .addComponent(add_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFrame2.getAccessibleContext().setAccessibleParent(add_phn);

        jFrame5.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame5.setTitle("Update Student");
        jFrame5.setBounds(new java.awt.Rectangle(0, 0, 255, 190));
        jFrame5.setLocation(new java.awt.Point(450, 250));
        jFrame5.setPreferredSize(new java.awt.Dimension(300, 243));
        jFrame5.setResizable(false);
        jFrame5.setSize(new java.awt.Dimension(300, 243));
        jFrame5.setType(java.awt.Window.Type.POPUP);

        jPanel6.setPreferredSize(new java.awt.Dimension(255, 190));

        jLabel13.setText("Name:");

        jLabel14.setText("Department:");

        jLabel15.setText("National ID:");

        jLabel16.setText("Phone Number:");

        update_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_nameActionPerformed(evt);
            }
        });

        update_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--choose a department--", "Computers", "Electrical", "Architecture", "Civil" }));

        update_save.setText("Save");
        update_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_saveActionPerformed(evt);
            }
        });

        update_cancel.setText("cancel");
        update_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update_id)
                    .addComponent(update_dept, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_phn))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_save)
                .addGap(31, 31, 31)
                .addComponent(update_cancel)
                .addGap(51, 51, 51))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(update_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(update_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(update_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(update_phn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_save)
                    .addComponent(update_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFrame5.getAccessibleContext().setAccessibleName("");

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame4.setTitle("Delete  Student");
        jFrame4.setLocation(new java.awt.Point(450, 250));
        jFrame4.setPreferredSize(new java.awt.Dimension(265, 146));
        jFrame4.setResizable(false);
        jFrame4.setSize(new java.awt.Dimension(265, 146));
        jFrame4.setType(java.awt.Window.Type.POPUP);

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 101));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Are you sure for deleting?");

        delete_yes.setText("Yes");
        delete_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_yesActionPerformed(evt);
            }
        });

        delete_no.setText("No");
        delete_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_noActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(delete_yes)
                .addGap(33, 33, 33)
                .addComponent(delete_no)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(jLabel12))
                .addGap(123, 123, 123))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_yes)
                    .addComponent(delete_no))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setBounds(new java.awt.Rectangle(0, 0, 180, 250));
        setLocation(new java.awt.Point(450, 250));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(260, 190));
        setResizable(false);
        setSize(new java.awt.Dimension(260, 190));

        jLabel1.setText("username:");

        jLabel2.setText("password:");

        lgn_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgn_passActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lgn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lgn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(submit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lgn_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lgn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_idActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        try {
            session = factory.getCurrentSession();
            session.beginTransaction();

            // search for student testing consol
            mainApp m = new mainApp();
            m.getStudents(session, search_id.getText());

            searchTable(search_id.getText());

            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_goActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try {
            session = factory.getCurrentSession();
            session.beginTransaction();

            jFrame2.setVisible(true);

            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_addActionPerformed

    private void add_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_nameActionPerformed

    private void delete_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_noActionPerformed
        // TODO add your handling code here:
        jFrame4.dispose();
    }//GEN-LAST:event_delete_noActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        try {
            search_id.setText("");
            update_id.setText("");
            update_name.setText("");
            update_dept.setSelectedIndex(0);
            update_phn.setText("");

            displayTable();
            jFrame1.setVisible(true);
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_clearActionPerformed

    private void add_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_saveActionPerformed
        // TODO add your handling code here:
        try {
            String pr;
            mainApp m = new mainApp();
            session = factory.getCurrentSession();
            session.beginTransaction();
            if (add_id.getText().length() == 14) {
                if (!add_name.getText().equals("")) {
                    if (add_dept.getSelectedIndex() != 0) {
                        if (add_phn.getText().length() == 11 && add_phn.getText().startsWith("01")) {
                            boolean c = m.createStudent(session, add_id.getText(), add_name.getText(), (String) add_dept.getSelectedItem(), add_phn.getText());
                            if (c) {
                                pr = "New Student has been saved";
                                System.out.println(pr);
                                JOptionPane.showMessageDialog(null, pr);

                                add_cancelActionPerformed(evt);
                                jFrame1.setVisible(true);
                                clearActionPerformed(evt);
                            } else {
                                pr = "You can not add a new Student because there is an existing one with this Id: " + add_id.getText();
                                System.out.println(pr);
                                JOptionPane.showMessageDialog(null, pr);
                            }
                        } else {
                            pr = "Phone number should be of 11 digits and starts with '01' ";
                            System.out.println(pr);
                            JOptionPane.showMessageDialog(null, pr);
                        }
                    } else {
                        pr = "choose a department!";
                        System.out.println(pr);
                        JOptionPane.showMessageDialog(null, pr);
                    }
                } else {
                    pr = "Student name can not be empty";
                    System.out.println(pr);
                    JOptionPane.showMessageDialog(null, pr);
                }

            } else {
                pr = "ID should be of 14 digits";
                System.out.println(pr);
                JOptionPane.showMessageDialog(null, pr);
            }

            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_add_saveActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:

        try {
            session = factory.getCurrentSession();
            session.beginTransaction();
            mainApp m = new mainApp();
            m.LoginAuthentication(session, lgn_user.getText(), lgn_pass.getText(), this, jFrame1);
            displayTable();
            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void lgn_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgn_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgn_passActionPerformed

    private void add_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cancelActionPerformed
        // TODO add your handling code here:
        add_name.setText(null);
        add_id.setText(null);
        add_dept.setSelectedIndex(0);
        add_phn.setText(null);
        jFrame2.dispose();
    }//GEN-LAST:event_add_cancelActionPerformed

    private void update_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_nameActionPerformed

    private void update_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_saveActionPerformed
        // TODO add your handling code here:
        try {
            mainApp m = new mainApp();
            session = factory.getCurrentSession();
            session.beginTransaction();
            String op;
            if (update_dept.getSelectedIndex() != 0) {
                boolean u = m.updateStudent(session, update_id.getText(), update_name.getText(), (String) update_dept.getSelectedItem(), update_phn.getText());
                if (u) {
                    op = "Student Updated Successfully!!";
                    System.out.println(op);
                    JOptionPane.showMessageDialog(null, op);
                    update_cancelActionPerformed(evt);
                    clearActionPerformed(evt);
                } else {
                    op = "The Student does not exist!";
                    System.out.println(op);
                    JOptionPane.showMessageDialog(null, op);
                }
            } else {
                op = "choose a department!";
                System.out.println(op);
                JOptionPane.showMessageDialog(null, op);
            }
            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_saveActionPerformed

    private void update_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_cancelActionPerformed
        // TODO add your handling code here:
        jFrame5.dispose();
    }//GEN-LAST:event_update_cancelActionPerformed

    private void delete_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_yesActionPerformed
        // TODO add your handling code here:
        try {
            String s;
            mainApp m = new mainApp();
            session = factory.getCurrentSession();
            session.beginTransaction();
            boolean x = m.deleteStudent(session, update_id.getText());
            if (x) {
                s = "Student deleted Successfully!!";
                System.out.println(s);
                JOptionPane.showMessageDialog(null, s);
                jFrame4.dispose();
            } else {
                s = "The Student does not exist!";
                System.out.println(s);
                JOptionPane.showMessageDialog(null, s);
            }
            session.close();
            clearActionPerformed(evt);
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delete_yesActionPerformed

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            session = factory.getCurrentSession();
            session.beginTransaction();
            String s;
            if (update_id.getText().equals("")) {
                s = "choose a student to update";
                System.out.println(s);
                JOptionPane.showMessageDialog(null, s);
            } else {
                jFrame5.setVisible(true);
                update_id.disable();
            }
            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            session = factory.getCurrentSession();
            session.beginTransaction();
            String s;
            if (update_id.getText().equals("")) {
                s = "choose a student to delete";
                System.out.println(s);
                JOptionPane.showMessageDialog(null, s);
            } else {
                jLabel8.setText("'" + update_name.getText() + "'");
                jLabel8.setSize(17, update_name.getText().length());
                jFrame4.setVisible(true);
                jLabel8.setVisible(true);
            }
            session.close();
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    static SessionFactory factory = new Configuration()
            .configure("hibernate.cfg.xml")
            .addAnnotatedClass(Login.class
            )
            .addAnnotatedClass(Student.class
            )
            .buildSessionFactory();

    private Session session;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {

            /* Create and display the form */
        } finally {
            //Session.close();
            //factory.close();
        }
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    public void clicked() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(final MouseEvent e) {
                if (e.getClickCount() == 1) {
                    final JTable jTable = (JTable) e.getSource();
                    final int row = jTable.getSelectedRow();
                    //final int column = jTable.getSelectedColumn();
                    final String IdCell = (String) jTable.getValueAt(row, 0);
                    final String nameCell = (String) jTable.getValueAt(row, 1);
                    final String deptCell = (String) jTable.getValueAt(row, 2);
                    final String phoneCell = (String) jTable.getValueAt(row, 3);
                    update_id.setText(IdCell);
                    update_name.setText(nameCell);
                    update_dept.setSelectedItem(deptCell);
                    update_phn.setText(phoneCell);
                }
            }
        }
        );
    }

    public void displayTable() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_task?useSSL=false",
                    "hbstudent", "hbstudent");
            String sql = "SELECT * FROM student_task.student";
            PreparedStatement prst = conn.prepareStatement(sql);
            ResultSet rs = prst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            clicked();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void searchTable(String name) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_task?useSSL=false",
                    "hbstudent", "hbstudent");
            String query = "SELECT * FROM Student where name like '%" + name + "%'" + " or id like '%" + name + "%'";
            PreparedStatement prst = conn.prepareStatement(query);
            ResultSet rs = prst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            update_id.setText("");
            update_name.setText("");
            update_dept.setSelectedIndex(0);
            update_phn.setText("");
            clicked();
            if (jTable1.getRowCount() == 1) {
                update_id.setText((String) jTable1.getValueAt(0, 0));
                update_name.setText((String) jTable1.getValueAt(0, 1));
                update_dept.setSelectedItem((String) jTable1.getValueAt(0, 2));
                update_phn.setText((String) jTable1.getValueAt(0, 3));
            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add_cancel;
    private javax.swing.JComboBox<String> add_dept;
    private javax.swing.JTextField add_id;
    private javax.swing.JTextField add_name;
    private javax.swing.JTextField add_phn;
    private javax.swing.JButton add_save;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete_no;
    private javax.swing.JButton delete_yes;
    private javax.swing.JButton go;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField lgn_pass;
    private javax.swing.JTextField lgn_user;
    private javax.swing.JTextField search_id;
    private javax.swing.JButton submit;
    private javax.swing.JButton update;
    private javax.swing.JButton update_cancel;
    private javax.swing.JComboBox<String> update_dept;
    private javax.swing.JTextField update_id;
    private javax.swing.JTextField update_name;
    private javax.swing.JTextField update_phn;
    private javax.swing.JButton update_save;
    // End of variables declaration//GEN-END:variables
}
